app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security_login:
    path:  /login/
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path:  /logout/
    defaults: { _controller: FOSUserBundle:Security:logout }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /loginhwi

facebook_login:
    path: /login/check-facebook

# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /chat
        permanent: true



