security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        api:
            id: my.custom.user_provider

    firewalls:
         main:
              logout:
                  path: /logout/
                  target: /login
              form_login:
                  provider: api
                  csrf_token_generator: security.csrf.token_manager
                  login_path: /login
                  check_path: /login_check
                  default_target_path: /
              oauth:
                  resource_owners:
                      facebook:           "/login/check-facebook"
                  login_path:        /login
                  use_forward:       false
                  failure_path:      /login
                  default_target_path: /
                  oauth_user_provider:
                      service: my.custom.user_provider
              anonymous:    ~

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/chat, role: ROLE_USER }

